In [1]:
import numpy as np

# 1- Create and array using Numpy arrays

In [10]:
empty = np.empty((2,3)) 
print(empty)
# Empty dosent means that the array is empty , it is near to zero or zero sometmes as well, it means that the array is not initialized.
# Initialze means that the array is not filled with zeros or ones. It contain random number.

[[6.95293874e-310 4.43363519e-249 1.44263870e-311]
 [1.44263870e-311 1.03753786e-322 4.44659081e-323]]


### 1.1 Gettig the calue froman array on using `INDEX` method

In [9]:
print(empty[0])

[-6.95293874e-310  4.43363519e-249  1.44263870e-311]


# 2. Creating a range using the `Numpy array`

In [13]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [16]:
b = np.arange(5,6)
b
#The code `b = np.arange(5,6)` creates a NumPy array `b` with a single element, which is the number 5. 
# The `arange()` function creates an array of values with a specified range and step size. 
# In this case, the range is from 5 (inclusive) to 6 (exclusive), and since the step size is not specified, it defaults to 1. 
# Therefore, the resulting array has a single element, which is 5.

array([5])

### 2.1 : Creating a range using the step value 

In [20]:
c = np.arange (5,12,2)
c
# Here we created a range of array.
# Starting point is 5.
# Ending point is 12.
# Interval is 2.

array([ 5,  7,  9, 11])

In [22]:
d = np.arange(5,12,2.5)
d
# Another example

array([ 5. ,  7.5, 10. ])

# 3 Linspace in Numpy arrays. Not LINESPACE it is LINspace without "E". It is used to create liner trend data posituve and negative as well.

where `start` is the starting value of the interval, `stop` is the ending value of the interval, `num` is the number of values to generate, `i` is the index of the current value being generated (starting from 0), and `y` is the current value being generated.

`linspace()` is used to create an array of evenly spaced values over a specified interval. It is commonly used in scientific computing and data analysis applications. The purpose of `linspace()` is to generate a set of values that are evenly spaced between a specified start and stop value, which can be useful for creating plots, performing numerical simulations, and other tasks that require a set of evenly spaced values.

In [27]:
linspace = np.linspace(2,15, num=9)
linspace
# Here we created a range of array.
# Starting point is 2.
# Ending point is 15.
# Number of elements is 9. Means the output will be 9 elements. or 9 numbers.
# The difference between the numbers is equal.

print(linspace)

[ 2.     3.625  5.25   6.875  8.5   10.125 11.75  13.375 15.   ]


The formula that NumPy uses to calculate the evenly spaced values in `linspace()` is:

y = start + (stop - start) * (i / (num - 1))


### 3.1: Linear Trend using the negative value of the positive

In [31]:
linspace2 = np.linspace(2, -15, num= 10)
linspace2


array([  2.        ,   0.11111111,  -1.77777778,  -3.66666667,
        -5.55555556,  -7.44444444,  -9.33333333, -11.22222222,
       -13.11111111, -15.        ])

# 4. Array data types

In [35]:
array

dtype('float64')

In [34]:
a.dtype

dtype('int32')

### 4.1 : Defining a data type in Numpy arrays

In [36]:
x = np.arange(1,10, dtype=np.float64)
x

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
x1 = np.arange(10, dtype=np.int64)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [42]:
x2 = np.arange(1,10, 3, np.dtype('int64'))
x2

array([1, 4, 7], dtype=int64)

# 5. Sorting In Numpy

In [45]:
array = np.array([6,4,22, 12])
array.sort()
array

array([ 4,  6, 12, 22])

# 6- Conacatination in Numpy arrays

### 6.1: Concatinate one dimesnsion array to another

In [46]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])


In [47]:
np.concatenate((a,b))   


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 6.2: Concatinate two dimensional arrays

In [50]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

c = np.concatenate((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### 6.2 : Concatenating on the axis with NumPy arrays

In [54]:
d = np.concatenate((a,b), axis=0)
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:
d = np.concatenate((a,b), axis=1)
d

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# 7 : Reshaping an array 



In [61]:
a1 = np.array([(1,2,3,4,5,6,7,8,9,10) ,(11,12,13,14,15,16,17,18,19,20)])
a2 = np.array([(21,22,23,24,25,26,27,28,29,30) ,(31,32,33,34,35,36,37,38,39,40)])

a3 = np.concatenate([a1,a2])
a3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [67]:
a3.shape


(4, 10)

In [70]:
a3.reshape(10,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40]])

# 8. Coverting 1D to 2D with NUMPY

# 9. Indexing and Slicing in Numpy arrays

# 10. Using filters to filtter in the array and filtering and or filtering